/*
 * This file is generated by jOOQ.
*/
package com.kotlin.zcj.tc.data.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTcUser implements Serializable {

    private static final long serialVersionUID = 166902304;

    private String    userId;
    private String    loginName;
    private String    password;
    private String    email;
    private String    phone;
    private Integer   age;
    private Timestamp birthday;
    private String    createBy;
    private Timestamp createTime;
    private String    updateBy;
    private Timestamp updateTime;

    public TTcUser() {}

    public TTcUser(TTcUser value) {
        this.userId = value.userId;
        this.loginName = value.loginName;
        this.password = value.password;
        this.email = value.email;
        this.phone = value.phone;
        this.age = value.age;
        this.birthday = value.birthday;
        this.createBy = value.createBy;
        this.createTime = value.createTime;
        this.updateBy = value.updateBy;
        this.updateTime = value.updateTime;
    }

    public TTcUser(
        String    userId,
        String    loginName,
        String    password,
        String    email,
        String    phone,
        Integer   age,
        Timestamp birthday,
        String    createBy,
        Timestamp createTime,
        String    updateBy,
        Timestamp updateTime
    ) {
        this.userId = userId;
        this.loginName = loginName;
        this.password = password;
        this.email = email;
        this.phone = phone;
        this.age = age;
        this.birthday = birthday;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Timestamp getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Timestamp birthday) {
        this.birthday = birthday;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTcUser (");

        sb.append(userId);
        sb.append(", ").append(loginName);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(age);
        sb.append(", ").append(birthday);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
