/*
 * This file is generated by jOOQ.
*/
package com.kotlin.zcj.tc.data;


import com.kotlin.zcj.tc.data.tables.TTcAccount;
import com.kotlin.zcj.tc.data.tables.TTcUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1802617948;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.t_tc_account</code>.
     */
    public final TTcAccount T_TC_ACCOUNT = com.kotlin.zcj.tc.data.tables.TTcAccount.T_TC_ACCOUNT;

    /**
     * The table <code>public.t_tc_user</code>.
     */
    public final TTcUser T_TC_USER = com.kotlin.zcj.tc.data.tables.TTcUser.T_TC_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TTcAccount.T_TC_ACCOUNT,
            TTcUser.T_TC_USER);
    }
}
